# Generated by Django 4.2 on 2023-05-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='telephone',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
