# Generated by Django 4.2 on 2023-05-16 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiteModule', '0003_settings_facebook_settings_googleplus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='pinterset',
            new_name='pintereset',
        ),
    ]
