# Generated by Django 4.2 on 2023-04-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_rename_articlecategories_productcategories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategories',
            options={'verbose_name': 'product category', 'verbose_name_plural': 'product categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'product ', 'verbose_name_plural': 'products'},
        ),
        migrations.RemoveField(
            model_name='productcategories',
            name='url',
        ),
        migrations.AddField(
            model_name='productcategories',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='url categories'),
        ),
        migrations.AlterField(
            model_name='productcategories',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title categories'),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
        ),
    ]
