# Generated by Django 4.2 on 2023-05-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_alter_productcategories_slug_alter_products_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='content',
        ),
        migrations.RemoveField(
            model_name='products',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
        migrations.RemoveField(
            model_name='products',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='products',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='products',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='grade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='packing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='products',
            name='categories',
        ),
        migrations.AddField(
            model_name='products',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Products.productcategories', verbose_name='categories'),
        ),
    ]
